### ISSUE TITLE
Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found [Production]

### ISSUE THREAD

**Issue by kamerk22** [beyondcode/laravel-dump-server#38]
@mpociot  I guess know the problem. I've install composer with no dev dependencies. But that's what I need for my Production Docker Image. I've also try to change `.env` to production from local.
Thanks for the package it's awesome!

Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found

```bash
composer install  --no-dev --no-scripts --no-plugins
``` 
![screenshot_2018-12-05 screenshot](https://user-images.githubusercontent.com/11503211/49509497-889eba80-f8ab-11e8-8679-2d67929df9e9.png)

**Comment by mpociot** [comment]
@kamerk22 Have you tried calling `php artisan clear-compiled`? Seems like you have the service provider still cached somewhere. Since it gets automatically registered when installing the package this can only mean that your application still thinks the package is installed.

**Comment by pablofmorales** [comment]
```
[2018-12-28 09:07:30] staging.ERROR: Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'BeyondCode\\DumpServer\\DumpServerServiceProvider' not found at /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:638)
[stacktrace]
#0 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(570): Illuminate\\Foundation\\Application->resolveProvider('BeyondCode\\\\Dump...')
#1 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register('BeyondCode\\\\Dump...')
#2 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(550): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(204): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#5 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#6 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /var/www/web-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#8 /var/www/web-api/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#9 {main}
"}
^C
root@ip-172-31-10-183:/var/www/web-api# ^C
root@ip-172-31-10-183:/var/www/web-api# php artisan clear-compiled

In Application.php line 638:

  Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found
```

Amazing

**Comment by PatBriPerso** [comment]
I have the same problem: during making a Docker image for production, any `php artisan` command failed with the `Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found` error.

I finally find that it was due to /bootstrap/cache files I copy from my local Laravel app to the Docker image. My cached files was generated with require-dev dependencies so reference the 'BeyondCode\DumpServer\DumpServerServiceProvider' class.

My solution: remove `/bootstrap/cache` files from my Docker image.

```
COPY . /var/www/html
RUN rm /var/www/html/bootstrap/cache/*
```

**Comment by GrigorAtaryan** [comment]
You should update your composer>
Just run `composer Update`
Response is 

>  Discovered Package: beyondcode/laravel-dump-server
